/**
 * REAL Stripe Webhook Test
 *
 * Starts a local HTTP server, uses `stripe listen --forward-to` to receive
 * real Stripe-signed webhook events, and processes them through our
 * processWebhookEvent() handler.
 *
 * This tests the ACTUAL Stripe signature verification + event processing
 * with events generated by the Stripe CLI — no mocking, no simulation.
 *
 * Usage:
 *   bun test/live/webhook-real-stripe.ts
 */

import { tmpdir } from "node:os";
import { join } from "node:path";
import { unlinkSync, existsSync } from "node:fs";
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { spawn, type ChildProcess } from "node:child_process";

// Isolated temp DB
const TEST_DB = join(tmpdir(), `jeriko-webhook-real-${Date.now()}.db`);
process.env.JERIKO_DB_PATH = TEST_DB;
if (!process.env.STRIPE_BILLING_SECRET_KEY) throw new Error("Set STRIPE_BILLING_SECRET_KEY env var");

import { initDatabase, closeDatabase } from "../../src/daemon/storage/db.js";
import { processWebhookEvent } from "../../src/daemon/billing/webhook.js";

initDatabase(TEST_DB);

// ---------------------------------------------------------------------------
// State tracking
// ---------------------------------------------------------------------------

interface ReceivedEvent {
  type: string;
  handled: boolean;
  error?: string;
  timestamp: number;
}

const received: ReceivedEvent[] = [];
let webhookSecret: string | null = null;

// ---------------------------------------------------------------------------
// HTTP server — receives forwarded Stripe events
// ---------------------------------------------------------------------------

const PORT = 19876; // unlikely to conflict

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on("data", (c: Buffer) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString()));
    req.on("error", reject);
  });
}

const server = createServer(async (req: IncomingMessage, res: ServerResponse) => {
  if (req.method !== "POST") {
    res.writeHead(404);
    res.end();
    return;
  }

  const body = await readBody(req);
  const sig = req.headers["stripe-signature"] as string ?? "";

  if (!webhookSecret) {
    console.log("  WARNING: No webhook secret yet, skipping event");
    res.writeHead(200);
    res.end(JSON.stringify({ ok: true }));
    return;
  }

  // Set the webhook secret for our handler to use
  process.env.STRIPE_BILLING_WEBHOOK_SECRET = webhookSecret;

  const result = processWebhookEvent(body, sig);

  // Parse event type from body
  let eventType = "unknown";
  try {
    const parsed = JSON.parse(body);
    eventType = parsed.type ?? "unknown";
  } catch { /* ignore */ }

  received.push({
    type: eventType,
    handled: result.handled,
    error: result.error,
    timestamp: Date.now(),
  });

  const status = result.handled ? "PROCESSED" : `REJECTED (${result.error})`;
  console.log(`  <- ${eventType}: ${status}`);

  res.writeHead(200);
  res.end(JSON.stringify({ ok: true }));
});

// ---------------------------------------------------------------------------
// Stripe CLI listener
// ---------------------------------------------------------------------------

function startStripeListener(): Promise<ChildProcess> {
  return new Promise((resolve, reject) => {
    const proc = spawn("stripe", [
      "listen",
      "--forward-to", `http://127.0.0.1:${PORT}/webhook`,
      "--api-key", process.env.STRIPE_BILLING_SECRET_KEY!,
    ], {
      stdio: ["ignore", "pipe", "pipe"],
    });

    let output = "";
    const timeout = setTimeout(() => {
      reject(new Error("Stripe CLI did not output webhook secret within 15s"));
    }, 15000);

    function checkForSecret(text: string): void {
      output += text;
      const match = output.match(/whsec_\S+/);
      if (match && !webhookSecret) {
        webhookSecret = match[0];
        clearTimeout(timeout);
        console.log(`  Webhook secret: ${webhookSecret.slice(0, 20)}...`);
        resolve(proc);
      }
    }

    // Stripe CLI outputs the secret on stderr (not stdout)
    proc.stdout!.on("data", (data: Buffer) => checkForSecret(data.toString()));
    proc.stderr!.on("data", (data: Buffer) => checkForSecret(data.toString()));

    proc.on("error", (err) => {
      clearTimeout(timeout);
      reject(err);
    });
  });
}

// ---------------------------------------------------------------------------
// Trigger events via Stripe CLI
// ---------------------------------------------------------------------------

async function triggerEvent(eventType: string): Promise<boolean> {
  return new Promise((resolve) => {
    const proc = spawn("stripe", [
      "trigger", eventType,
      "--api-key", process.env.STRIPE_BILLING_SECRET_KEY!,
    ], {
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    proc.stdout!.on("data", (d: Buffer) => { stdout += d.toString(); });
    proc.stderr!.on("data", (d: Buffer) => { stderr += d.toString(); });

    proc.on("close", (code) => {
      if (code !== 0) {
        console.log(`  TRIGGER FAILED (${eventType}): ${stderr.trim()}`);
        resolve(false);
      } else {
        resolve(true);
      }
    });
  });
}

function wait(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

// ---------------------------------------------------------------------------
// Main test
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log("\n  REAL STRIPE WEBHOOK TEST");
  console.log("  (using Stripe CLI for real signed events)\n");

  // Start HTTP server
  await new Promise<void>((resolve) => server.listen(PORT, "127.0.0.1", resolve));
  console.log(`  HTTP server on port ${PORT}`);

  // Start Stripe CLI listener
  let stripeProc: ChildProcess;
  try {
    console.log("  Starting Stripe CLI listener...");
    stripeProc = await startStripeListener();
    console.log("  Stripe CLI ready\n");
  } catch (err) {
    console.log(`  FAIL: Could not start Stripe listener: ${err}`);
    server.close();
    cleanup();
    process.exit(1);
  }

  // Events to trigger — these are the ones our billing webhook handler processes
  const eventsToTest = [
    "checkout.session.completed",
    "customer.subscription.created",
    "customer.subscription.updated",
    "invoice.paid",
    "invoice.payment_failed",
    "customer.subscription.deleted",
  ];

  console.log("--- TRIGGERING EVENTS ---");
  for (const eventType of eventsToTest) {
    console.log(`\n  -> Triggering: ${eventType}`);
    const ok = await triggerEvent(eventType);
    if (!ok) {
      console.log(`  WARNING: Failed to trigger ${eventType} — skipping`);
      continue;
    }
    // Wait for the event to be forwarded + processed
    await wait(3000);
  }

  // Wait a bit more for any trailing events
  console.log("\n  Waiting for trailing events...");
  await wait(5000);

  // Kill Stripe listener
  stripeProc.kill("SIGTERM");
  server.close();

  // ---------------------------------------------------------------------------
  // Analyze results
  // ---------------------------------------------------------------------------
  console.log("\n--- RESULTS ---");
  console.log(`  Total events received: ${received.length}`);

  // Group by type
  const byType = new Map<string, ReceivedEvent[]>();
  for (const e of received) {
    const list = byType.get(e.type) ?? [];
    list.push(e);
    byType.set(e.type, list);
  }

  let allGood = true;

  for (const [type, events] of byType) {
    const handled = events.filter((e) => e.handled).length;
    const rejected = events.filter((e) => !e.handled).length;
    const status = rejected === 0 ? "PASS" : "WARN";
    if (rejected > 0) allGood = false;
    console.log(`  ${status}: ${type} — ${handled} handled, ${rejected} rejected`);
    for (const e of events.filter((e) => !e.handled)) {
      console.log(`    Error: ${e.error}`);
    }
  }

  // Check that we received events for the types we triggered
  const expectedTypes = new Set([
    "checkout.session.completed",
    "customer.subscription.created",
    "customer.subscription.updated",
    "customer.subscription.deleted",
    "invoice.paid",
    "invoice.payment_failed",
  ]);

  const receivedTypes = new Set(received.map((e) => e.type));
  const missing = [...expectedTypes].filter((t) => !receivedTypes.has(t));

  if (missing.length > 0) {
    console.log(`\n  MISSING events (not received): ${missing.join(", ")}`);
    // Some events may arrive as side effects of others, so this is informational
  }

  // Final tally of handled events
  const totalHandled = received.filter((e) => e.handled).length;
  const totalRejected = received.filter((e) => !e.handled).length;
  console.log(`\n  Summary: ${totalHandled} handled, ${totalRejected} rejected out of ${received.length} total`);

  cleanup();

  if (totalHandled > 0 && allGood) {
    console.log("\n================================================");
    console.log("  ALL REAL STRIPE WEBHOOKS PROCESSED CORRECTLY");
    console.log("================================================\n");
  } else if (totalHandled > 0) {
    console.log("\n================================================");
    console.log(`  ${totalHandled} PROCESSED, ${totalRejected} REJECTED — check warnings above`);
    console.log("================================================\n");
  } else {
    console.log("\n  FAIL: No events were handled");
    process.exit(1);
  }
}

function cleanup(): void {
  try { closeDatabase(); } catch { /* ignore */ }
  if (existsSync(TEST_DB)) {
    try { unlinkSync(TEST_DB); } catch { /* ignore */ }
  }
}

main().catch((err) => {
  console.error(`FATAL: ${err}`);
  cleanup();
  process.exit(1);
});
