import { connectorCommand } from "./_connector.js";

export const command = connectorCommand("stripe", "Stripe (charges, customers, invoices, subscriptions)", [
  "\nCall Stripe API methods through the connector.",
  "\nResources & Actions:",
  "  charges       list | create | get <id>",
  "  customers     list | create | get <id>",
  "  subscriptions list | create | get <id> | cancel <id>",
  "  invoices      list | create | get <id> | finalize <id> | send <id> | void <id>",
  "  products      list | create | get <id> | update <id> | delete <id>",
  "  prices        list | create | get <id>",
  "  payment_intents  create | get <id> | confirm <id>",
  "  refunds       create | get <id> | list",
  "  payouts       list | create | get <id>",
  "  events        list | get <id>",
  "  webhooks      list | create | delete <id>",
  "  checkout      create | get <id> | list",
  "  payment_links create | list | get <id>",
  "  balance       get",
  "\nFlags:",
  "  --id <id>         Resource ID",
  "  --limit <n>       Max results",
  "  --amount <cents>  Amount in cents",
  "  --currency <code> Currency (default: usd)",
  "  --customer <id>   Customer ID",
  "  --email <addr>    Customer email",
  "  --name <text>     Resource name",
  "  --description <t> Description",
]);
