/**
 * Mascot — ASCII art builder for Jeriko's cat logo.
 *
 * The Jeriko cat logo, rendered with Unicode block characters (█ ▀ ▄ ▌ ▐)
 * for high-resolution terminal display. Downscaled from the source artwork
 * (ascii-art-cli.txt) using half-block character compositing — each
 * display row represents two pixel rows from the original.
 *
 * Pre-colored with the brand palette: purple body, blue accents,
 * dim shadow edges. All lines padded to uniform visual width for
 * column alignment in the welcome banner.
 *
 * Two sizes:
 *   buildMascot()        — full logo (11 lines, 47 chars) for welcome banner
 *   buildMascotCompact() — compact logo (11 lines, 24 chars) for inline use
 */

import { t } from "../theme.js";
import { stripAnsi } from "../format.js";

// ---------------------------------------------------------------------------
// Main API
// ---------------------------------------------------------------------------

/**
 * Build the Jeriko cat logo as an array of chalk-styled lines.
 * All lines are padded to the same visual width for column alignment.
 *
 * Downscaled from ascii-art-cli.txt via vertical half-block compositing.
 * Each display row = 2 pixel rows. 47 chars wide, 11 lines tall.
 */
export function buildMascot(): string[] {
  const raw = colorize(RAW_LINES);
  return normalizeWidth(raw);
}

/**
 * Build a compact cat logo (fewer lines) for narrow terminals or inline use.
 * 2x2 half-block compositing: 24 chars wide, 11 lines tall.
 */
export function buildMascotCompact(): string[] {
  const raw = colorize(RAW_COMPACT);
  return normalizeWidth(raw);
}

// ---------------------------------------------------------------------------
// Raw art data — exact output from half-block compositing of ascii-art-cli.txt
// ---------------------------------------------------------------------------

/**
 * Full 11-line logo. Each line is exactly 47 visual characters.
 * Generated by vertical half-block compositing (2 rows → 1 row):
 *   both filled → █, top only → ▀, bottom only → ▄, neither → space
 */
const RAW_LINES: string[] = [
  "    ▄▄▄▄▄▄                       ▄▄▄███▄       ",
  "    █████████▄▄    ▄▄▄▄▄▄      ▀█████████      ",
  "    ███▀▀▀█████████████████████▄▄▄▄██████      ",
  "    ▀▄▄▄████████████████████████████████▄      ",
  "   ▄███████████████████████████████████████▄   ",
  " ▄██████████▀▀▀▀▀▀▀▀█████████████████████████▄▄",
  "████████████████████▄███████▄▄▄▄▄▄▄ ▀▀█████████",
  " ▀███████████████████████████████████████████▀ ",
  "   ▀███████████████████████████████████████▀   ",
  "       ▀▀▀▀███████████████████████████▀▀▀      ",
  "                  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀              ",
];

/**
 * Compact 11-line logo (24 chars). 2x2 half-block compositing.
 */
const RAW_COMPACT: string[] = [
  "  ███           ▐███    ",
  "  █████▌ ▐██▌  ▐████▌   ",
  "  ██████████████████▌   ",
  "  ██████████████████▌   ",
  " ▐████████████████████  ",
  "▐██████████████████████▌",
  "█████████████████▌█████▌",
  "▐██████████████████████ ",
  " ▐████████████████████  ",
  "   ▐████████████████▌   ",
  "         ███████▌       ",
];

// ---------------------------------------------------------------------------
// Colorize — apply theme colors to raw block art
// ---------------------------------------------------------------------------

/**
 * Apply white/silver coloring to the cat art.
 * Body (█) = white text color, edges (▀▄) = silver/muted.
 */
function colorize(lines: string[]): string[] {
  return lines.map((line) => {
    let result = "";
    let i = 0;
    while (i < line.length) {
      const ch = line[i]!;
      if (ch === " ") {
        let spaces = "";
        while (i < line.length && line[i] === " ") {
          spaces += " ";
          i++;
        }
        result += spaces;
      } else if (ch === "▀" || ch === "▄") {
        let run = "";
        while (i < line.length && (line[i] === "▀" || line[i] === "▄")) {
          run += line[i];
          i++;
        }
        result += t.muted(run);
      } else if (ch === "█") {
        let run = "";
        while (i < line.length && line[i] === "█") {
          run += line[i];
          i++;
        }
        result += t.text(run);
      } else if (ch === "▌" || ch === "▐") {
        result += t.muted(ch);
        i++;
      } else {
        result += ch;
        i++;
      }
    }
    return result;
  });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Pad all lines to the same visual width (ignoring ANSI escapes).
 */
function normalizeWidth(lines: string[]): string[] {
  const maxWidth = Math.max(...lines.map((l) => stripAnsi(l).length));
  return lines.map((l) => {
    const pad = Math.max(0, maxWidth - stripAnsi(l).length);
    return l + " ".repeat(pad);
  });
}
